### ISSUE TITLE
Can't get started!

### ISSUE THREAD

**Issue by BeggarsMattM** [jarektkaczyk/laravel-kahlan#10]
Sorry to bug you with what must be something silly, but I've fallen at the very first hurdle!

Following your documentation as closely as I can (Laravel 5.4) I keep on getting     

`message:`Error` Code(0) with message "Call to undefined method Illuminate\\Http\\Response::see()"`

Am I not doing something I should be doing? Pretty sure the kahlan-config.php file is being run. Your docs seem idiot-proof so I'm quite confused. Thanks!

**Comment by jarektkaczyk** [comment]
@BeggarsMattM updated readme - it was ok for earlier versions, but since Laravel doesn't give a sh.t about sticking to one convention, `see` and `assertResponseOk` methods are simply gone ;)
