### ISSUE TITLE
Undefined variable `crawler`.

### ISSUE THREAD

**Issue by tsunamilx** [jarektkaczyk/laravel-kahlan#12]
Hi

I ran your demo spec `AppSpec.php` and saw the following error:

![image](https://cloud.githubusercontent.com/assets/6290337/26023750/d07a0aee-37f5-11e7-8f5b-f3ec14e08b0a.png)

Am I missing something?

**Comment by gabriel-kaam** [comment]
Hey @tsunamilx , try with `$this->laravel->get('/');`

Ran into the same issue couple days ago

**Comment by tsunamilx** [comment]
@gabriel-kaam Nice!
