### ISSUE TITLE
Test case status pending

### ISSUE THREAD

**Issue by nikhil-incedo** [jarektkaczyk/laravel-kahlan#13]
`$this->laravel->get('/mypage')->assertStatus(200)`
Above code give me pending status instead of getting passed. Though the code below execute alright (either give pass or error).
`expect($this->laravel->get('/mypage')->assertStatus(200))->toBeTruthy(); `

I guess this is not how it is supposed to work.

**Comment by mlabita37** [comment]
Hi @jarektkaczyk, I'm having the same issue using Laravel 5.4, could this be related to Laravel version updates? As @nikhil-incedo has stated, wrapping the **assertStatus(200)** in an **expect()->toBeTruthy()** works, but this seems redundant. Any help would be greatly appreciated. Thanks!

**Comment by jarektkaczyk** [comment]
hi @nikhil-incedo @mlabita37 
Thanks for your input, it is indeed an issue since L v5.3 I guess, but I havent had the time to look into it.
Is there are chance that you guys find the issue?
