### ISSUE TITLE
Using 'DatabaseTransactions' and `toThrow` matcher

### ISSUE THREAD

**Issue by pluxain** [jarektkaczyk/laravel-kahlan#2]
I don't know it this is an issue, but this is something I need to understand at least.

Using the Laravel Testing, this works:
```php
class BrandTest extends TestCase
{
    use DatabaseTransactions;

    /** @test */
    public function its_name_is_unique()
    {
        App\Brand::create(['name' => 'unique']);
        $this->setExpectedException(Illuminate\Database\QueryException);
        App\Brand::create(['name' => 'unique']);
        $this->assertEquals(1, App\Brand::count());
    }

}
```
Using Laravel Kahlan testing (thanks to your package), this does not work :
``` php
describe('Brand Model', function() {
    
    using('DatabaseTransactions', function() {
   
        it('has a unique name', function() {
            App\Brand::create(['name' => 'unique']);
            expect(function() { App\Brand::create(['name' => 'unique']); })->toThrow();
            expect(App\Brand::count())->toBe(1);
        });
    });
});
```

I get this error with Laravel/Kahlan
```
Brand Model
  Following specs run using: DatabaseTransactions ⤵
    ✘ it has a unique name
      an uncaught exception has been thrown in 
      `/vendor/laravel/framework/src/Illuminate/Database/Connection.php` line 761
      
      message:`Illuminate\Database\QueryException` Code(25P02) with message 
      "SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted,
      commands ignored until end of transaction block (SQL: select count(*) as aggregate 
      from \"brands\")"
```

I understand as an error is thrown the DB transaction might be aborted as explains the message, and then the next 'count' request is rejected, but why does it work with PHPUnit and not Kahlan.

**Comment by jarektkaczyk** [comment]
@pluxain your code works for me. Make sure the first `create(['name' => 'unique'])` is not causing this exception to be thrown.

**Comment by pluxain** [comment]
@jarektkaczyk thanks for your time.

I am sure the first `create(['name' => 'unique'])` is not causing the error : the database is fresh and it is the only test I run.

But what I found out is that in the PHPUnit test, the assertions after the error is thrown are not met. So in fact it does not "work", it is just not executed.

I still have the error with Laravel/Kahlan. I can live without testing the count but it is really difficult to test the `Illuminate\Database\QueryException` the unique constraint throws in the `toThrow()` matcher. I guess I will have to make a Custom Matcher then...

Thanks for your plugin anyway

**Comment by jarektkaczyk** [comment]
Let me know which versions you're using exactly I'll play with it

**Comment by pluxain** [comment]
This is the composer.json file (extract)
```json
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "laravel/homestead": "^3.0",
        "sofa/laravel-kahlan": "^5.3"
    },
```

This is the migration for the Brand Model (very simple indeed)
```php
Schema::create('brands', function (Blueprint $table) 
    $table->increments('id');
    $table->string('name')->unique();
    $table->timestamps();
});
```

This is the kahlan-config.php file
```php
<?php

Sofa\LaravelKahlan\Env::bootstrap($this);

// Do not Monkey Patch
$this->args()->set('include', []);

```

**Comment by jarektkaczyk** [comment]
All good using your setup. Something must be wrong on your end, maybe that's the case for PHPUnit as well:

here's the repo to reproduce this behaviour https://github.com/jarektkaczyk/super-couscous

![image](https://cloud.githubusercontent.com/assets/6928818/18388301/ad274a36-76d3-11e6-9ab3-c7ae67557db8.png)


```php
describe('Brand Model', function() {

    using('DatabaseTransactions', function() {

        it('has a unique name', function() {
            App\Brand::create(['name' => 'unique']);
            expect(function() { App\Brand::create(['name' => 'unique']); })->toThrow();
            expect(App\Brand::count())->toBe(1);
        });

        it('this will actually break', function() {
            App\Brand::create(['name' => 'unique']);
            expect(function() { App\Brand::create(['name' => 'unique']); })->not->toThrow();
        });
    });
});
```

**Comment by pluxain** [comment]
Well I finally found a way to better use the `toThrow` matcher of Kahlan so get to write the test I wanted and it is much better. The thing I had to realize is the **RegExp pattern for the message** of the Exception expected AND the **code has to be a string** here.

```php
describe('Brand Model', function() {

    using('DatabaseTransactions', function() {

        it('has a unique name', function() {
            App\Brand::create(['name' => 'unique']);
            expect(function() { App\Brand::create(['name' => 'unique']); })
                ->toThrow('/Unique violation/', '23505');
        });

    });

});
```

**Comment by pluxain** [comment]
I tested you repo and customized it to match my .env settings (using pgsql for database driver and homestead virtual machine).
I run the test while sshed to homestead instance and I have the same failure.

I think this has something to do with pgsql's transactions handling.

Thanks for your support and help.
