### ISSUE TITLE
More Robust Testing Example

### ISSUE THREAD

**Issue by ljieyao** [jarektkaczyk/laravel-kahlan#20]
I am really interested in this framework as there is none of describe-it syntax testing framework for Laravel. However, the testing example you provided is minimal, which I am not really sure how to use it in a real world app, for example, testing controller with validation, testing traits, etc. I wish you could provide a better testing example for people to follow. 

Furthermore, hope that this package can support 5.6 soon. thanks

**Comment by jarektkaczyk** [comment]
Hi @ljieyao 

To be honest with so many unnecessary changes to Laravel, it's hard to keep up with maintaining packages like this one, which depend on the core functionality of the FW.
You can play with it, most of functionalities are available by calling `$this->laravel->_whatever_you_would_call_on_laravel_TestCase()`.

If there's demand for this, I would love some PRs and we can move it forward together.
